[build]
command = "yarn build" # the command you run to build this file
functions = "netlify/functions" # netlify-lambda builds to this folder AND Netlify reads functions from here
publish = "dist" # create-react-app builds to this folder, Netlify should serve all these files statically

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[functions]
included_files = ["netlify/**"]